---
apiVersion: v1
kind: Secret
metadata:
  name: trino-config
stringData:
  config-coordinator.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080

    #http-server.authentication.type=oauth2
    #http-server.https.port=8443
    #http-server.https.enabled=true
    #http-server.https.keystore.path=/etc/pki/tls/cert.pem
    #http-server.authentication.oauth2.auth-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/auth
    #http-server.authentication.oauth2.token-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/token
    #http-server.authentication.oauth2.jwks-url=http://dex-dex.apps.odh-cl1.apps.os-climate.org/keys
    #http-server.authentication.oauth2.client-id=trino
    #http-server.authentication.oauth2.client-secret=${ENV:TRINO_OAUTH_SECRET}
    #web-ui.authentication.type=oauth2
  config-worker.properties: |-
    coordinator=false
    http-server.http.port=8080
    discovery.uri=http://trino-service:8080
  jvm.config: |-
    -server
    -Xmx16G
    -XX:-UseBiasedLocking
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
  log.properties: |-
    io.trino=INFO
  node.properties: |-
    node.environment=$(trino_environment)
    node.data-dir=/tmp/data/trino
